<?php
	// Lindy and Blues Event Edit Price Info Script
	// Version 1.0.1
	// Date Created:  12-26-2013 by Marc Longhenry
	// 
	// The purpose of this script is to take information generated by the Edit Event form and associated
	// systems and update the Event information in the 'events' database.
	//
	// Date		Developer  				Modified
	// -------- ----------------------  --------------------------------------------------------------------------
	// 12-26-13 Marc Longhenry  		File Created, modified to use the database tables and files for updating Event information.
	
	// Get Database Connection Info and Set database table
	include('db.php');
	$mysqli = new mysqli($hostname, $username, $password, $dbname);
	if ($mysqli->connect_errno) {
		echo "Failed to connect to MySQL please contact us with the following error: (" . $mysqli->connect_errno . ") " . $mysqli->connect_error;
	}
	
	// Receive POST data and assign to variables.
	$event_id = $_POST['event_id'];
	$s_time = $_POST['s_time'];
	$e_time = $_POST['e_time'];
	$teachers = $_POST['teachers'];
	$music = $_POST['music'];
	$location = $_POST['location'];
	$description = $_POST['description'];
	$housing = $_POST['housing'];
	$contact_name = $_POST['contact_name'];
	$contact_email = $_POST['contact_email'];

	// Create a New Event with given information.
	// Create a prepared statement.  Avoids SQL injection.
	if ($stmt = $mysqli->prepare("UPDATE prices SET s_time = ?, e_time = ?, teachers = ?, music = ?, location = ?, description = ?, housing = ?, contact_name = ?, contact_email = ? WHERE event_id = ?")) {
		if (!$stmt->bind_param("ssssssssss", $s_time, $e_time, $teachers, $music, $location, $description, $housing, $contact_name, $contact_email, $event_id)) {
			echo "Binding parameters failed: (" . $stmt->errno . ") " . $stmt->error;
		}
		if (!$stmt->execute()) {
    		echo "Execute failed: (" . $stmt->errno . ") " . $stmt->error;
   		}
		$stmt->close();
	} else {
		echo "Error, unable to create mysqli statement";	
	}
	
	// Redirect Submiter to Create/Edit page
	header("Location: /create-edit-event");

?>